JWT_SECRET = "123456789"

[Database]
User = "root"
Password = "root"
Host = "localhost"
Port = "3306"
Name = "swetelove"
Charset = "utf8mb4"

[Redis]
Addr = "localhost:6379"
DB = "0"

[ES]
Url = "http://localhost:9200"